baseURL = "http://ftard.me/"
languageCode = "en-us"
title = "ftard.me"
theme = "hello-friend-ng"

[author]
  name = "dawjanox"
  homepage = "https://dawja.com"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

paginate  = 10
rssLimit  = 10  # Maximum number of items in the RSS feed.
#copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International unmaicense." # This message is only used by the RSS template.

# googleAnlytics  = ""
disqusShortname = "ftard.me"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false

disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false


#the blinker
[params.logo]
  logoText              =  "ftard.me:"
  logoHomeLink          =  "/"
  logoCursorColor       =  "#42f554"
  logoCursorAnimate     =  "2s"

#portrait image
[params.portrait]
  path          =  "img/ff-v1-300.png"
  alt           =  "portrait"
  maxWidth      =  "400px"

[[params.social]]
    name = "discord"
    url  = "https://discord.gg/invite/3HGXsPe"

[menu]
  [[menu.main]]
    identifier  = "about"
    name        = "about"
    url         = "about/about/"
  [[menu.main]]
    identifier  = "posts"
    name        = "posts"
    url         = "posts/"
  


[params]

# Metadata mostly used in document's head
#
description = "I like bacons"
keywords = ""
images = ["img"]

# Footer
footerLeft      = "Powered by <a href=\"http://gohugo.io\">Hugo</a>"
footerRight     = "theme <a href=\"https://themes.gohugo.io/hugo-theme-hello-friend-ng/\">hello-friend-ng</a>"

# Sharing buttons
#
# There are a lot of buttons preconfigured. If you want to change them,
# generate the buttons here: https://sharingbuttons.io
# and add them into your own `layouts/partials/sharing-buttons.html`
#
enableSharingButtons = true

# Integrate Javascript files or stylesheets by adding the url to the external assets or by
# linking local files with their path relative to the static folder, e.g. "css/styles.css"
#
customCSS = []
customJS  = []

homeSubtitle = "Go ahead Alice, take a sip!"

  # Set a background for the homepage
backgroundImage = "img/skull_bg1a.png"

enableThemeToggle = true

[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'